### ISSUE TITLE
Roadmap to post-quantum public key cryptography?

### ISSUE THREAD

**Issue by oittaa** [tink-crypto/tink#478]
The [roadmap](https://github.com/google/tink/blob/72383d6eb144a803bad541481f52ef238f5ae7f1/docs/ROADMAP.md) hasn't been updated in a while and I was wondering if there are any plans to add post-quantum algorithms? For example German Federal Office for Information Security (BSI) [has started to recommend FrodoKEM](https://www.bsi.bund.de/SharedDocs/Downloads/EN/BSI/Publications/TechGuidelines/TG02102/BSI-TR-02102-1.pdf?__blob=publicationFile&v=10) "as cryptographically suitable for long-term confidentiality protection".

My understanding is that Google has already tested some hybrid solutions in Chrome so maybe it wouldn't be too complex to add a hybrid solution that uses FrodoKEM (or some other suitable algorithm) as a component.

**Comment by thaidn** [comment]
Believe it or not, we're actively working on this. Tink will support PQC digital signature and public key encryption.

At the moment it's not part of our external release, because we want to experiment with it internally for awhile, and will release when it's stable.

**Comment by oittaa** [comment]
Thanks for the update!

**Comment by hernandezteo** [comment]
I'm wondering why should Tink support PQC digital signatures when they are not as necessary or polished as the public key algorithms (I read a leading algorithm was badly hurt just a few weeks ago). Is there any demand for it right now? I'm just worried about people using "undercooked" crypto.

I really enjoy Tink btw. Thank you for the awesome work.

**Comment by rafa-mczk** [comment]
Hi @hernandezteo, 

Different cryptosystems offer different levels of maturity. Saying that PQC digital signature algorithms are necessarily less polished than their encryption counterparts is not really correct. For example, consider the case of hash-based signature algorithms. Those are PQC digital signature algorithms that rely on minimal security assumptions, in particular their security is solely based on some well-known properties related hash functions such as pre-image resistance, while all other PQC families (lattices, codes, isogenies, multivariate-quadratic) rely on additional security assumptions that may have not gone through as much scrutiny as those problems related to hash functions. Hash-based signatures, in particular their stateful incarnations (like XMSS and LMS schemes), are suitable to real-world applications like code signing and software update applications in general. 

Note however that, despite of the optimal security some PQC digital signature algorithm (e.g. HBS) achieve, I agree with you that they are less urgent than key exchange algorithms, for example. This is because that forging signatures requires an online (quantum) adversary, while key-exchange/encryption we don't need one as a store-now-decrypt-later attack becomes relevant. 

We are glad you enjoy the Tink project! :)

**Comment by redwrasse** [comment]
Thank you for this thread (now two years old) on adding PQC to Tink. If there's a nascent open source on this front, as opposed to internal effort, would be interested.

**Comment by kste** [comment]
To close this out before https://github.com/tink-crypto/tink/issues/730: The [current roadmap](https://developers.google.com/tink/roadmap#post-quantum_cryptography_pqc) provides some information about the PQC support, and there is experimental support for signatures and a hybrid encryption scheme (hybrid in the sense of public-key + symmetric-key encryption) in https://github.com/tink-crypto/tink-cc/tree/main/tink/experimental/pqcrypto.

We will provide support for the algorithms which NIST standardized (i.e. ML-KEM, ML-DSA, SLH-DSA), soon after the final standards are published (we expect this to happen in H1'24) and then remove the experimental support.
